[package]
name = "luser-api"
version = "0.1.0"
edition = "2024"

[dependencies]
luser-config ={ path = "../luser-config"}
tokio = { workspace = true}
serde =  { workspace = true}
anyhow =  { workspace = true}
thiserror = { workspace = true}
tracing = { workspace = true}